//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyPortfolioNet1Entities2 : DbContext
    {
        public MyPortfolioNet1Entities2()
            : base("name=MyPortfolioNet1Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TblAbout> TblAbouts { get; set; }
        public DbSet<TblBanner> TblBanners { get; set; }
        public DbSet<TblCategory> TblCategories { get; set; }
        public DbSet<TblContact> TblContacts { get; set; }
        public DbSet<TblEducation> TblEducations { get; set; }
        public DbSet<TblExperience> TblExperiences { get; set; }
        public DbSet<TblExpertis> TblExpertises { get; set; }
        public DbSet<TblMessage> TblMessages { get; set; }
        public DbSet<TblProject> TblProjects { get; set; }
        public DbSet<TblSocialMedia> TblSocialMedias { get; set; }
        public DbSet<TblTestimonial> TblTestimonials { get; set; }
        public DbSet<TblAdmin> TblAdmins { get; set; }
    }
}
